global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'cloudpulse-sre-monitor'

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:4000', 'host.docker.internal:4000']

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-service:4001', 'host.docker.internal:4001']

  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['payment-service:4002', 'host.docker.internal:4002']
