/**
 * ⚠️  DEMO / SIMULATED TELEMETRY PROVIDER
 *
 * This file contains structured, correlated telemetry models for local SRE exploration.
 * In production, this data is ingested from Prometheus, OpenTelemetry Collector, Loki, and Tempo.
 */

import type {
  Service,
  MetricSummary,
  LogEntry,
  Trace,
  Alert,
  Incident,
  SloDefinition,
  InfrastructureResource,
  SystemComponentStatus,
  FaultInjectionConfig,
  OverviewData,
  MetricDatapoint,
} from '@cloudpulse/shared';

const now = new Date();
const ago = (minutes: number): string =>
  new Date(now.getTime() - minutes * 60 * 1000).toISOString();

// ── Fault Simulation State ───────────────────────────────────────────────────

export const activeFaults: FaultInjectionConfig = {
  latencySpike: false,
  errorRateBurst: false,
  serviceOutage: null,
  dbPoolExhaustion: true,
  trafficSpike: false,
};

// ── Time-Series Generators ───────────────────────────────────────────────────

function generateTimeSeries(pointsCount: number, base: number, variance: number, trend = 0): MetricDatapoint[] {
  const points: MetricDatapoint[] = [];
  const intervalMs = (15 * 60 * 1000) / pointsCount; // last 15 mins
  const startTime = now.getTime() - 15 * 60 * 1000;

  for (let i = 0; i < pointsCount; i++) {
    const time = new Date(startTime + i * intervalMs).toISOString();
    const noise = (Math.sin(i / 2) + Math.cos(i / 3)) * variance;
    const trendVal = (i / pointsCount) * trend;
    const value = Math.max(0, Math.round((base + noise + trendVal) * 100) / 100);
    points.push({ timestamp: time, value });
  }
  return points;
}

// ── Services Catalog ─────────────────────────────────────────────────────────

export const servicesData: Service[] = [
  {
    id: 'svc-api-gateway',
    name: 'api-gateway',
    description: 'Edge reverse proxy, SSL termination, and rate-limiting ingress controller',
    team: 'Platform / Edge',
    environment: 'production',
    tier: 'tier-1',
    version: 'v2.14.1',
    status: 'healthy',
    uptimePercent: 99.98,
    requestRate: 4850,
    errorRate: 0.12,
    latencyP50Ms: 12,
    latencyP95Ms: 45,
    latencyP99Ms: 78,
    activeAlertCount: 0,
    dependencies: [
      { targetServiceId: 'svc-auth', targetServiceName: 'auth-service', type: 'grpc', callRateRps: 1240, errorRatePercent: 0.02, p99LatencyMs: 25 },
      { targetServiceId: 'svc-order', targetServiceName: 'order-service', type: 'http', callRateRps: 2150, errorRatePercent: 0.85, p99LatencyMs: 140 },
      { targetServiceId: 'svc-inventory', targetServiceName: 'inventory-service', type: 'http', callRateRps: 1460, errorRatePercent: 0.05, p99LatencyMs: 38 },
    ],
    goldenSignals: {
      throughputRps: 4850,
      errorRatePercent: 0.12,
      latencyP50Ms: 12,
      latencyP95Ms: 45,
      latencyP99Ms: 78,
      cpuUsagePercent: 38.4,
      memoryUsageMb: 512,
    },
    updatedAt: ago(0.2),
  },
  {
    id: 'svc-auth',
    name: 'auth-service',
    description: 'OAuth2 / JWT token validation, SSO federated identity, and policy evaluation',
    team: 'Identity & Security',
    environment: 'production',
    tier: 'tier-1',
    version: 'v1.8.3',
    status: 'healthy',
    uptimePercent: 99.99,
    requestRate: 1240,
    errorRate: 0.02,
    latencyP50Ms: 8,
    latencyP95Ms: 22,
    latencyP99Ms: 35,
    activeAlertCount: 0,
    dependencies: [
      { targetServiceId: 'res-redis-session', targetServiceName: 'redis-session-cluster', type: 'database', callRateRps: 1240, errorRatePercent: 0, p99LatencyMs: 2 },
    ],
    goldenSignals: {
      throughputRps: 1240,
      errorRatePercent: 0.02,
      latencyP50Ms: 8,
      latencyP95Ms: 22,
      latencyP99Ms: 35,
      cpuUsagePercent: 24.1,
      memoryUsageMb: 384,
    },
    updatedAt: ago(0.2),
  },
  {
    id: 'svc-order',
    name: 'order-service',
    description: 'Order lifecycle management, checkout orchestration, and fulfillment dispatcher',
    team: 'Core Commerce',
    environment: 'production',
    tier: 'tier-1',
    version: 'v3.2.0',
    status: 'degraded',
    uptimePercent: 99.45,
    requestRate: 2150,
    errorRate: 2.85,
    latencyP50Ms: 85,
    latencyP95Ms: 340,
    latencyP99Ms: 890,
    activeAlertCount: 2,
    dependencies: [
      { targetServiceId: 'svc-payment', targetServiceName: 'payment-service', type: 'http', callRateRps: 680, errorRatePercent: 8.4, p99LatencyMs: 1450 },
      { targetServiceId: 'svc-inventory', targetServiceName: 'inventory-service', type: 'grpc', callRateRps: 2150, errorRatePercent: 0.05, p99LatencyMs: 42 },
      { targetServiceId: 'res-rds-orders', targetServiceName: 'aurora-orders-pg', type: 'database', callRateRps: 4300, errorRatePercent: 0.1, p99LatencyMs: 18 },
    ],
    goldenSignals: {
      throughputRps: 2150,
      errorRatePercent: 2.85,
      latencyP50Ms: 85,
      latencyP95Ms: 340,
      latencyP99Ms: 890,
      cpuUsagePercent: 72.8,
      memoryUsageMb: 1280,
    },
    updatedAt: ago(0.1),
  },
  {
    id: 'svc-payment',
    name: 'payment-service',
    description: 'Payment gateway integrations, card tokenization, 3DS verification, and ledger records',
    team: 'Payments & Billing',
    environment: 'production',
    tier: 'tier-1',
    version: 'v2.9.4',
    status: 'unhealthy',
    uptimePercent: 98.24,
    requestRate: 680,
    errorRate: 8.40,
    latencyP50Ms: 240,
    latencyP95Ms: 880,
    latencyP99Ms: 1850,
    activeAlertCount: 3,
    dependencies: [
      { targetServiceId: 'res-rds-payments', targetServiceName: 'aurora-payments-pg', type: 'database', callRateRps: 1360, errorRatePercent: 12.2, p99LatencyMs: 1400 },
      { targetServiceId: 'res-sqs-settlement', targetServiceName: 'payment-settlement-queue', type: 'queue', callRateRps: 680, errorRatePercent: 0, p99LatencyMs: 8 },
    ],
    goldenSignals: {
      throughputRps: 680,
      errorRatePercent: 8.40,
      latencyP50Ms: 240,
      latencyP95Ms: 880,
      latencyP99Ms: 1850,
      cpuUsagePercent: 88.5,
      memoryUsageMb: 1840,
    },
    updatedAt: ago(0.1),
  },
  {
    id: 'svc-inventory',
    name: 'inventory-service',
    description: 'Real-time stock availability, warehouse reservation, and SKU catalog service',
    team: 'Supply Chain',
    environment: 'production',
    tier: 'tier-2',
    version: 'v1.12.0',
    status: 'healthy',
    uptimePercent: 99.95,
    requestRate: 1460,
    errorRate: 0.05,
    latencyP50Ms: 14,
    latencyP95Ms: 38,
    latencyP99Ms: 58,
    activeAlertCount: 0,
    dependencies: [
      { targetServiceId: 'res-rds-inventory', targetServiceName: 'dynamodb-inventory-table', type: 'database', callRateRps: 2920, errorRatePercent: 0.01, p99LatencyMs: 10 },
    ],
    goldenSignals: {
      throughputRps: 1460,
      errorRatePercent: 0.05,
      latencyP50Ms: 14,
      latencyP95Ms: 38,
      latencyP99Ms: 58,
      cpuUsagePercent: 31.2,
      memoryUsageMb: 640,
    },
    updatedAt: ago(0.3),
  },
  {
    id: 'svc-notification',
    name: 'notification-service',
    description: 'Email, SMS, mobile push notification dispatcher, and delivery tracking',
    team: 'Platform / Edge',
    environment: 'production',
    tier: 'tier-3',
    version: 'v1.4.1',
    status: 'healthy',
    uptimePercent: 99.92,
    requestRate: 420,
    errorRate: 0.18,
    latencyP50Ms: 28,
    latencyP95Ms: 85,
    latencyP99Ms: 120,
    activeAlertCount: 0,
    dependencies: [
      { targetServiceId: 'res-sqs-notifications', targetServiceName: 'notification-dispatch-queue', type: 'queue', callRateRps: 420, errorRatePercent: 0, p99LatencyMs: 6 },
    ],
    goldenSignals: {
      throughputRps: 420,
      errorRatePercent: 0.18,
      latencyP50Ms: 28,
      latencyP95Ms: 85,
      latencyP99Ms: 120,
      cpuUsagePercent: 19.5,
      memoryUsageMb: 410,
    },
    updatedAt: ago(0.4),
  },
];

// ── Metrics Explorer Summaries ───────────────────────────────────────────────

export const metricsData: MetricSummary[] = [
  {
    metricName: 'http_requests_total',
    displayName: 'HTTP Request Rate',
    description: 'Total incoming HTTP/HTTPS requests per second across all ingress and microservices',
    unit: 'req/s',
    category: 'http',
    currentValue: 10800,
    minValue: 8200,
    maxValue: 12400,
    avgValue: 9850,
    p50Value: 9700,
    p95Value: 11800,
    p99Value: 12350,
    changePercent: 12.4,
    series: generateTimeSeries(30, 10200, 800, 600),
  },
  {
    metricName: 'http_request_duration_ms',
    displayName: 'HTTP Latency (P99)',
    description: '99th percentile HTTP server response time measured at service boundary',
    unit: 'ms',
    category: 'http',
    currentValue: 287,
    minValue: 65,
    maxValue: 1850,
    avgValue: 184,
    p50Value: 42,
    p95Value: 160,
    p99Value: 287,
    changePercent: 8.2,
    series: generateTimeSeries(30, 210, 45, 75),
  },
  {
    metricName: 'http_errors_total',
    displayName: 'HTTP 5xx Error Rate',
    description: 'Percentage of requests returning 500, 502, 503, or 504 status codes',
    unit: '%',
    category: 'http',
    currentValue: 1.84,
    minValue: 0.08,
    maxValue: 8.40,
    avgValue: 1.25,
    p50Value: 0.12,
    p95Value: 3.40,
    p99Value: 7.80,
    changePercent: -0.4,
    series: generateTimeSeries(30, 1.6, 0.4, -0.2),
  },
  {
    metricName: 'cpu_usage_percent',
    displayName: 'Cluster CPU Utilization',
    description: 'Mean CPU utilization across all Kubernetes node pool instances',
    unit: '%',
    category: 'system',
    currentValue: 64.2,
    minValue: 42.0,
    maxValue: 88.5,
    avgValue: 58.1,
    p50Value: 55.0,
    p95Value: 78.0,
    p99Value: 86.4,
    changePercent: 5.1,
    series: generateTimeSeries(30, 60, 6, 4),
  },
  {
    metricName: 'memory_usage_bytes',
    displayName: 'Container Memory Footprint',
    description: 'Resident set memory size consumed by microservice container runtimes',
    unit: 'GB',
    category: 'system',
    currentValue: 28.6,
    minValue: 22.1,
    maxValue: 34.2,
    avgValue: 26.4,
    p50Value: 25.8,
    p95Value: 31.0,
    p99Value: 33.8,
    changePercent: 2.3,
    series: generateTimeSeries(30, 27.5, 1.8, 1.1),
  },
  {
    metricName: 'db_connection_pool_active',
    displayName: 'DB Connection Pool Saturation',
    description: 'Percentage of database connection slots currently checked out and active',
    unit: '%',
    category: 'database',
    currentValue: 94.2,
    minValue: 38.0,
    maxValue: 99.8,
    avgValue: 72.4,
    p50Value: 68.0,
    p95Value: 92.0,
    p99Value: 98.5,
    changePercent: 24.8,
    series: generateTimeSeries(30, 78, 10, 16),
  },
];

// ── Correlated Distributed Traces ────────────────────────────────────────────

export const tracesData: Trace[] = [
  {
    id: 'tr-checkout-9921',
    rootService: 'api-gateway',
    operation: 'POST /api/v1/checkout',
    startTime: ago(1.8),
    durationMs: 1480,
    statusCode: 'ERROR',
    spanCount: 6,
    depth: 4,
    servicesInvolved: ['api-gateway', 'auth-service', 'order-service', 'payment-service', 'postgres-payments'],
    spans: [
      {
        id: 'span-gw-01',
        traceId: 'tr-checkout-9921',
        parentId: null,
        serviceName: 'api-gateway',
        name: 'POST /api/v1/checkout',
        kind: 'SERVER',
        startTime: ago(1.8),
        startOffsetMs: 0,
        durationMs: 1480,
        statusCode: 'ERROR',
        statusMessage: 'Downstream HTTP 500 from order-service',
        attributes: {
          'http.method': 'POST',
          'http.route': '/api/v1/checkout',
          'http.status_code': 500,
          'http.url': 'https://api.cloudpulse.io/api/v1/checkout',
          'net.peer.name': '198.51.100.42',
        },
        children: [
          {
            id: 'span-auth-02',
            traceId: 'tr-checkout-9921',
            parentId: 'span-gw-01',
            serviceName: 'auth-service',
            name: 'POST /oauth/verify',
            kind: 'CLIENT',
            startTime: ago(1.8),
            startOffsetMs: 15,
            durationMs: 32,
            statusCode: 'OK',
            attributes: {
              'http.method': 'POST',
              'http.route': '/oauth/verify',
              'http.status_code': 200,
              'rpc.system': 'grpc',
            },
          },
          {
            id: 'span-order-03',
            traceId: 'tr-checkout-9921',
            parentId: 'span-gw-01',
            serviceName: 'order-service',
            name: 'POST /orders/create',
            kind: 'SERVER',
            startTime: ago(1.8),
            startOffsetMs: 52,
            durationMs: 1420,
            statusCode: 'ERROR',
            statusMessage: 'Payment authorization failed: timeout from payment-service',
            attributes: {
              'http.method': 'POST',
              'http.route': '/orders/create',
              'http.status_code': 500,
            },
            children: [
              {
                id: 'span-pay-04',
                traceId: 'tr-checkout-9921',
                parentId: 'span-order-03',
                serviceName: 'payment-service',
                name: 'POST /v1/charges',
                kind: 'CLIENT',
                startTime: ago(1.8),
                startOffsetMs: 120,
                durationMs: 1340,
                statusCode: 'ERROR',
                statusMessage: 'DB Connection acquisition timeout (1000ms exceeded)',
                attributes: {
                  'http.method': 'POST',
                  'http.route': '/v1/charges',
                  'http.status_code': 500,
                },
                children: [
                  {
                    id: 'span-db-05',
                    traceId: 'tr-checkout-9921',
                    parentId: 'span-pay-04',
                    serviceName: 'postgres-payments',
                    name: 'SELECT pool.checkout_connection',
                    kind: 'CLIENT',
                    startTime: ago(1.8),
                    startOffsetMs: 240,
                    durationMs: 1180,
                    statusCode: 'ERROR',
                    statusMessage: 'Error: ConnectionPoolExhausted: max 100 connections active',
                    attributes: {
                      'db.system': 'postgresql',
                      'db.name': 'payments_prod',
                      'db.statement': 'BEGIN; SELECT * FROM accounts WHERE id = $1 FOR UPDATE;',
                    },
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'tr-order-8842',
    rootService: 'api-gateway',
    operation: 'GET /api/v1/orders/ORD-99120',
    startTime: ago(4.2),
    durationMs: 64,
    statusCode: 'OK',
    spanCount: 4,
    depth: 3,
    servicesInvolved: ['api-gateway', 'auth-service', 'order-service', 'postgres-orders'],
    spans: [
      {
        id: 'span-gw-10',
        traceId: 'tr-order-8842',
        parentId: null,
        serviceName: 'api-gateway',
        name: 'GET /api/v1/orders/ORD-99120',
        kind: 'SERVER',
        startTime: ago(4.2),
        startOffsetMs: 0,
        durationMs: 64,
        statusCode: 'OK',
        attributes: { 'http.method': 'GET', 'http.status_code': 200 },
        children: [
          {
            id: 'span-auth-11',
            traceId: 'tr-order-8842',
            parentId: 'span-gw-10',
            serviceName: 'auth-service',
            name: 'POST /oauth/verify',
            kind: 'CLIENT',
            startTime: ago(4.2),
            startOffsetMs: 8,
            durationMs: 14,
            statusCode: 'OK',
            attributes: { 'http.status_code': 200 },
          },
          {
            id: 'span-order-12',
            traceId: 'tr-order-8842',
            parentId: 'span-gw-10',
            serviceName: 'order-service',
            name: 'GET /orders/:id',
            kind: 'SERVER',
            startTime: ago(4.2),
            startOffsetMs: 24,
            durationMs: 38,
            statusCode: 'OK',
            attributes: { 'http.status_code': 200 },
            children: [
              {
                id: 'span-db-13',
                traceId: 'tr-order-8842',
                parentId: 'span-order-12',
                serviceName: 'postgres-orders',
                name: 'SELECT orders',
                kind: 'CLIENT',
                startTime: ago(4.2),
                startOffsetMs: 30,
                durationMs: 22,
                statusCode: 'OK',
                attributes: { 'db.system': 'postgresql', 'db.statement': 'SELECT * FROM orders WHERE id = $1' },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'tr-inv-7721',
    rootService: 'api-gateway',
    operation: 'GET /api/v1/inventory/SKU-4912',
    startTime: ago(8.5),
    durationMs: 32,
    statusCode: 'OK',
    spanCount: 3,
    depth: 2,
    servicesInvolved: ['api-gateway', 'inventory-service', 'dynamodb-inventory'],
    spans: [
      {
        id: 'span-gw-20',
        traceId: 'tr-inv-7721',
        parentId: null,
        serviceName: 'api-gateway',
        name: 'GET /api/v1/inventory/SKU-4912',
        kind: 'SERVER',
        startTime: ago(8.5),
        startOffsetMs: 0,
        durationMs: 32,
        statusCode: 'OK',
        attributes: { 'http.method': 'GET', 'http.status_code': 200 },
        children: [
          {
            id: 'span-inv-21',
            traceId: 'tr-inv-7721',
            parentId: 'span-gw-20',
            serviceName: 'inventory-service',
            name: 'GET /stock/check',
            kind: 'SERVER',
            startTime: ago(8.5),
            startOffsetMs: 6,
            durationMs: 24,
            statusCode: 'OK',
            attributes: { 'http.status_code': 200 },
            children: [
              {
                id: 'span-db-22',
                traceId: 'tr-inv-7721',
                parentId: 'span-inv-21',
                serviceName: 'dynamodb-inventory',
                name: 'DynamoDB.GetItem',
                kind: 'CLIENT',
                startTime: ago(8.5),
                startOffsetMs: 12,
                durationMs: 14,
                statusCode: 'OK',
                attributes: { 'db.system': 'dynamodb', 'db.name': 'prod-inventory-table' },
              },
            ],
          },
        ],
      },
    ],
  },
];

// ── Correlated Logs ──────────────────────────────────────────────────────────

export const logsData: LogEntry[] = [
  {
    id: 'log-001',
    timestamp: ago(1.8),
    level: 'ERROR',
    service: 'payment-service',
    environment: 'production',
    message: 'CRITICAL: DB connection pool exhausted: 100/100 connections active. Acquire timeout after 1000ms',
    traceId: 'tr-checkout-9921',
    spanId: 'span-pay-04',
    requestId: 'req-e98fa201',
    attributes: {
      httpMethod: 'POST',
      httpPath: '/v1/charges',
      httpStatus: 500,
      latencyMs: 1340,
      host: 'payment-service-pod-7d8fb9c-49kz',
      errorType: 'ConnectionPoolTimeoutError',
      stackTrace: 'ConnectionPoolTimeoutError: Timeout acquiring client\n    at Pool.acquire (/app/node_modules/pg-pool/index.js:312:15)\n    at ChargeController.process (/app/dist/controllers/charge.js:42:20)',
    },
  },
  {
    id: 'log-002',
    timestamp: ago(1.8),
    level: 'ERROR',
    service: 'order-service',
    environment: 'production',
    message: 'Payment gateway rejected authorization token: downstream HTTP 500 from payment-service',
    traceId: 'tr-checkout-9921',
    spanId: 'span-order-03',
    requestId: 'req-e98fa201',
    attributes: {
      httpMethod: 'POST',
      httpPath: '/orders/create',
      httpStatus: 500,
      latencyMs: 1420,
      host: 'order-service-pod-5c7ea8a-92lx',
    },
  },
  {
    id: 'log-003',
    timestamp: ago(2.4),
    level: 'WARN',
    service: 'payment-service',
    environment: 'production',
    message: 'High DB checkout latency: acquire took 840ms (> 500ms warning threshold)',
    traceId: 'tr-checkout-9921',
    spanId: 'span-pay-04',
    attributes: {
      latencyMs: 840,
      host: 'payment-service-pod-7d8fb9c-49kz',
    },
  },
  {
    id: 'log-004',
    timestamp: ago(4.2),
    level: 'INFO',
    service: 'api-gateway',
    environment: 'production',
    message: 'HTTP GET /api/v1/orders/ORD-99120 completed 200 OK in 64ms',
    traceId: 'tr-order-8842',
    spanId: 'span-gw-10',
    requestId: 'req-71ac9012',
    attributes: {
      httpMethod: 'GET',
      httpPath: '/api/v1/orders/ORD-99120',
      httpStatus: 200,
      latencyMs: 64,
      clientIp: '198.51.100.18',
    },
  },
  {
    id: 'log-005',
    timestamp: ago(5.1),
    level: 'INFO',
    service: 'auth-service',
    environment: 'production',
    message: 'JWT Token verified successfully for subject user_998124',
    traceId: 'tr-order-8842',
    spanId: 'span-auth-11',
    attributes: {
      host: 'auth-service-pod-3a21b-80qq',
    },
  },
  {
    id: 'log-006',
    timestamp: ago(8.5),
    level: 'INFO',
    service: 'inventory-service',
    environment: 'production',
    message: 'Stock lookup hit cache for SKU-4912: 184 units available',
    traceId: 'tr-inv-7721',
    spanId: 'span-inv-21',
    attributes: {
      httpMethod: 'GET',
      httpPath: '/stock/check',
      httpStatus: 200,
      latencyMs: 24,
    },
  },
];

// ── Reliability: Alerts ──────────────────────────────────────────────────────

export const alertsData: Alert[] = [
  {
    id: 'alt-pay-err-01',
    name: 'PaymentServiceHighErrorRate',
    severity: 'critical',
    state: 'firing',
    serviceId: 'svc-payment',
    serviceName: 'payment-service',
    environment: 'production',
    summary: 'payment-service 5xx error rate is 8.40%, exceeding critical threshold of 3.00%',
    condition: 'rate(http_errors_total{service="payment-service"}[5m]) > 0.03',
    currentValue: 8.40,
    threshold: 3.00,
    unit: '%',
    firedAt: ago(16),
    resolvedAt: null,
    durationMinutes: 16,
    relatedTraceId: 'tr-checkout-9921',
    relatedLogId: 'log-001',
    incidentId: 'inc-1042',
  },
  {
    id: 'alt-pay-db-02',
    name: 'PaymentDbConnectionPoolExhaustion',
    severity: 'critical',
    state: 'firing',
    serviceId: 'svc-payment',
    serviceName: 'payment-service',
    environment: 'production',
    summary: 'aurora-payments-pg connection pool active saturation is 94.2% (> 90.0% critical threshold)',
    condition: 'db_connection_pool_active{service="payment-service"} > 90',
    currentValue: 94.2,
    threshold: 90.0,
    unit: '%',
    firedAt: ago(22),
    resolvedAt: null,
    durationMinutes: 22,
    relatedTraceId: 'tr-checkout-9921',
    relatedLogId: 'log-001',
    incidentId: 'inc-1042',
  },
  {
    id: 'alt-ord-lat-03',
    name: 'OrderServiceP99LatencyBreach',
    severity: 'high',
    state: 'firing',
    serviceId: 'svc-order',
    serviceName: 'order-service',
    environment: 'production',
    summary: 'order-service P99 latency is 890ms, exceeding 500ms SLA target',
    condition: 'histogram_quantile(0.99, http_request_duration_ms{service="order-service"}) > 500',
    currentValue: 890,
    threshold: 500,
    unit: 'ms',
    firedAt: ago(14),
    resolvedAt: null,
    durationMinutes: 14,
    relatedTraceId: 'tr-checkout-9921',
    incidentId: 'inc-1042',
  },
  {
    id: 'alt-slo-burn-04',
    name: 'PaymentSloErrorBudgetRapidBurn',
    severity: 'high',
    state: 'firing',
    serviceId: 'svc-payment',
    serviceName: 'payment-service',
    environment: 'production',
    summary: 'payment-service 1h error budget burn rate is 14.4x normal rate',
    condition: 'slo_burn_rate{service="payment-service",window="1h"} > 6.0',
    currentValue: 14.4,
    threshold: 6.0,
    unit: 'x',
    firedAt: ago(12),
    resolvedAt: null,
    durationMinutes: 12,
    incidentId: 'inc-1042',
  },
];

// ── Reliability: Incidents ───────────────────────────────────────────────────

export const incidentsData: Incident[] = [
  {
    id: 'inc-1042',
    title: 'Payment service connection pool exhaustion causing checkout failures',
    severity: 'sev1',
    state: 'investigating',
    affectedServices: ['payment-service', 'order-service', 'api-gateway'],
    summary: 'DB connection leak in payment worker pool causing cascading timeouts across order checkout pipeline',
    impact: 'Approximately 8.4% of checkout operations failing with 500 errors. Estimated $14k revenue impacted.',
    commander: 'alex.thornton (Staff SRE)',
    startedAt: ago(22),
    resolvedAt: null,
    durationMinutes: 22,
    relatedAlertIds: ['alt-pay-err-01', 'alt-pay-db-02', 'alt-ord-lat-03', 'alt-slo-burn-04'],
    relatedTraceIds: ['tr-checkout-9921'],
    relatedLogIds: ['log-001', 'log-002'],
    sloImpactSummary: 'payment-service 30-day availability SLO error budget exhausted (0% remaining)',
    postIncidentNotes: 'Investigation underway: DB connection pool max limit being increased and leak in tokenization retry logic identified for hotfix.',
    timeline: [
      {
        id: 'tl-01',
        timestamp: ago(22),
        type: 'created',
        title: 'Incident Declared SEV1',
        description: 'Automated page triggered by PaymentDbConnectionPoolExhaustion alert. Commander alex.thornton assumed incident lead.',
        author: 'CloudPulse Alert Engine',
      },
      {
        id: 'tl-02',
        timestamp: ago(18),
        type: 'alert_attached',
        title: 'Cascading Alerts Correlated',
        description: 'Attached PaymentServiceHighErrorRate and OrderServiceP99LatencyBreach alerts to incident timeline.',
        author: 'CloudPulse Correlation Engine',
      },
      {
        id: 'tl-03',
        timestamp: ago(14),
        type: 'mitigation',
        title: 'Traffic Shedding Enabled',
        description: 'Rate-limiting non-critical payment reconciliation tasks to preserve DB connection slots for live checkouts.',
        author: 'priya.mehta (Payments Lead)',
      },
      {
        id: 'tl-04',
        timestamp: ago(6),
        type: 'note',
        title: 'Hotfix Candidate Identified',
        description: 'Patch PR #412 prepared to release unclosed connections during payment gateway network retries.',
        author: 'alex.thornton (Staff SRE)',
      },
    ],
  },
];

// ── SRE: SLOs ────────────────────────────────────────────────────────────────

export const slosData: SloDefinition[] = [
  {
    id: 'slo-pay-avail',
    name: 'payment-service 30-day availability',
    serviceId: 'svc-payment',
    serviceName: 'payment-service',
    type: 'availability',
    targetPercent: 99.90,
    currentPercent: 98.24,
    errorBudgetRemainingPercent: 0,
    errorBudgetRemainingMinutes: 0,
    burnRate: 14.4,
    windowDays: 30,
    status: 'breached',
    description: 'Percentage of successful 2xx/3xx/4xx responses over total requests excluding client 400s',
    achievementHistory: generateTimeSeries(20, 98.5, 0.4, -0.6),
    burnDownHistory: generateTimeSeries(20, 10, 5, -15),
    updatedAt: ago(0.2),
  },
  {
    id: 'slo-ord-lat',
    name: 'order-service latency P99 < 500ms',
    serviceId: 'svc-order',
    serviceName: 'order-service',
    type: 'latency',
    targetPercent: 99.50,
    currentPercent: 97.40,
    errorBudgetRemainingPercent: 14.2,
    errorBudgetRemainingMinutes: 61,
    burnRate: 3.8,
    windowDays: 30,
    status: 'at_risk',
    description: '99% of order creation and query calls must complete in under 500ms',
    achievementHistory: generateTimeSeries(20, 97.6, 0.3, -0.4),
    burnDownHistory: generateTimeSeries(20, 30, 6, -18),
    updatedAt: ago(0.2),
  },
  {
    id: 'slo-gw-avail',
    name: 'api-gateway edge availability',
    serviceId: 'svc-api-gateway',
    serviceName: 'api-gateway',
    type: 'availability',
    targetPercent: 99.99,
    currentPercent: 99.98,
    errorBudgetRemainingPercent: 82.4,
    errorBudgetRemainingMinutes: 356,
    burnRate: 0.8,
    windowDays: 30,
    status: 'met',
    description: 'Edge gateway ingress uptime across all regional entry points',
    achievementHistory: generateTimeSeries(20, 99.98, 0.01, 0),
    burnDownHistory: generateTimeSeries(20, 84, 2, -1.5),
    updatedAt: ago(0.2),
  },
  {
    id: 'slo-auth-avail',
    name: 'auth-service token validation availability',
    serviceId: 'svc-auth',
    serviceName: 'auth-service',
    type: 'availability',
    targetPercent: 99.95,
    currentPercent: 99.99,
    errorBudgetRemainingPercent: 94.6,
    errorBudgetRemainingMinutes: 408,
    burnRate: 0.4,
    windowDays: 30,
    status: 'met',
    description: 'OAuth2 and JWT token validation latency < 50ms and error rate < 0.05%',
    achievementHistory: generateTimeSeries(20, 99.99, 0.005, 0),
    burnDownHistory: generateTimeSeries(20, 95, 1, -0.8),
    updatedAt: ago(0.2),
  },
];

// ── Infrastructure Inventory ─────────────────────────────────────────────────

export const infrastructureData: InfrastructureResource[] = [
  {
    id: 'res-k8s-prod-us-east-1',
    name: 'k8s-prod-cluster-us-east-1',
    type: 'k8s_cluster',
    category: 'compute',
    environment: 'production',
    status: 'healthy',
    region: 'us-east-1',
    zone: 'us-east-1a,1b,1c',
    version: 'v1.30.2-eks',
    metrics: { cpuPercent: 64.2, memoryPercent: 78.4, uptimeDays: 142 },
    tags: { 'k8s.io/role': 'production', 'team': 'platform' },
    updatedAt: ago(0.5),
  },
  {
    id: 'res-node-worker-01',
    name: 'ip-10-0-12-84.ec2.internal',
    type: 'k8s_node',
    category: 'compute',
    environment: 'production',
    status: 'warning',
    region: 'us-east-1',
    zone: 'us-east-1a',
    ipAddress: '10.0.12.84',
    version: 'v1.30.2',
    metrics: { cpuPercent: 88.5, memoryPercent: 92.1, diskPercent: 64.0, restarts: 2, uptimeDays: 45 },
    tags: { 'node.kubernetes.io/instance-type': 'c6i.4xlarge', 'workload': 'payment-service' },
    updatedAt: ago(0.5),
  },
  {
    id: 'res-node-worker-02',
    name: 'ip-10-0-14-192.ec2.internal',
    type: 'k8s_node',
    category: 'compute',
    environment: 'production',
    status: 'healthy',
    region: 'us-east-1',
    zone: 'us-east-1b',
    ipAddress: '10.0.14.192',
    version: 'v1.30.2',
    metrics: { cpuPercent: 42.0, memoryPercent: 58.6, diskPercent: 41.2, restarts: 0, uptimeDays: 45 },
    tags: { 'node.kubernetes.io/instance-type': 'c6i.4xlarge', 'workload': 'api-gateway' },
    updatedAt: ago(0.5),
  },
  {
    id: 'res-rds-payments',
    name: 'aurora-payments-pg-cluster',
    type: 'aws_rds',
    category: 'database',
    environment: 'production',
    status: 'critical',
    region: 'us-east-1',
    zone: 'multi-az',
    version: 'PostgreSQL 16.3',
    metrics: { cpuPercent: 89.2, memoryPercent: 94.8, diskPercent: 38.0 },
    tags: { 'engine': 'aurora-postgresql', 'db.name': 'payments_prod', 'service': 'payment-service' },
    updatedAt: ago(0.5),
  },
  {
    id: 'res-alb-ingress',
    name: 'prod-edge-alb-ingress',
    type: 'aws_alb',
    category: 'network',
    environment: 'production',
    status: 'healthy',
    region: 'us-east-1',
    metrics: { cpuPercent: 18.4, memoryPercent: 32.0, networkIoMbps: 480 },
    tags: { 'scheme': 'internet-facing', 'ssl': 'enabled' },
    updatedAt: ago(0.5),
  },
  {
    id: 'res-redis-session',
    name: 'redis-session-cluster',
    type: 'redis_cache',
    category: 'database',
    environment: 'production',
    status: 'healthy',
    region: 'us-east-1',
    version: 'Redis 7.2',
    metrics: { cpuPercent: 14.5, memoryPercent: 48.0 },
    tags: { 'cluster.mode': 'enabled', 'nodes': '6' },
    updatedAt: ago(0.5),
  },
];

// ── System Status (Internal CloudPulse Self-Observability) ────────────────────

export const systemStatusData: SystemComponentStatus[] = [
  {
    id: 'comp-web',
    name: 'CloudPulse Web Console',
    category: 'core',
    status: 'operational',
    latencyMs: 14,
    version: '0.0.2',
    details: 'React 18 SPA serving on Vite / Nginx runtime',
    mode: 'real',
  },
  {
    id: 'comp-api',
    name: 'CloudPulse Gateway API',
    category: 'core',
    status: 'operational',
    latencyMs: 8,
    version: '0.0.2',
    details: 'Node.js / Express REST API with typed schema validation',
    mode: 'real',
  },
  {
    id: 'comp-alert-engine',
    name: 'Real-time Alert Evaluator',
    category: 'engine',
    status: 'operational',
    latencyMs: 18,
    version: '1.0.0',
    details: 'Continuous PromQL condition evaluator and state machine',
    mode: 'real',
  },
  {
    id: 'comp-otel',
    name: 'OpenTelemetry Collector',
    category: 'collector',
    status: 'operational',
    latencyMs: 24,
    version: 'v0.104.0',
    details: 'OTLP Receiver gRPC:4317 / HTTP:4318 with batch processor',
    mode: 'simulated',
  },
  {
    id: 'comp-prom',
    name: 'Prometheus Metrics Engine',
    category: 'storage',
    status: 'operational',
    latencyMs: 32,
    version: 'v2.53.1',
    details: 'Time-series TSDB scraping target endpoints every 15s',
    mode: 'simulated',
  },
  {
    id: 'comp-loki',
    name: 'Loki Log Aggregator',
    category: 'storage',
    status: 'operational',
    latencyMs: 45,
    version: 'v3.0.0',
    details: 'Compressed indexed chunk store for structured stream search',
    mode: 'simulated',
  },
  {
    id: 'comp-tempo',
    name: 'Tempo Distributed Tracing',
    category: 'storage',
    status: 'operational',
    latencyMs: 38,
    version: 'v2.5.0',
    details: 'High-scale trace storage with S3 block backend',
    mode: 'simulated',
  },
];

// ── Overview Builder ─────────────────────────────────────────────────────────

export function buildOverviewData(): OverviewData {
  const healthy = servicesData.filter((s) => s.status === 'healthy').length;
  const degraded = servicesData.filter((s) => s.status === 'degraded').length;
  const unhealthy = servicesData.filter((s) => s.status === 'unhealthy').length;

  const totalRps = servicesData.reduce((sum, s) => sum + s.requestRate, 0);
  const avgErrorRate =
    servicesData.reduce((sum, s) => sum + s.errorRate, 0) / servicesData.length;
  const maxP99 = Math.max(...servicesData.map((s) => s.latencyP99Ms));
  const avgP50 =
    servicesData.reduce((sum, s) => sum + s.latencyP50Ms, 0) / servicesData.length;

  const activeAlertsCount = alertsData.filter((a) => a.state === 'firing').length;
  const criticalAlertsCount = alertsData.filter((a) => a.state === 'firing' && a.severity === 'critical').length;
  const openIncidentsCount = incidentsData.filter((i) => i.state !== 'resolved').length;
  const sev1Count = incidentsData.filter((i) => i.state !== 'resolved' && i.severity === 'sev1').length;

  return {
    systemHealth: {
      overallStatus: unhealthy > 0 ? 'unhealthy' : degraded > 0 ? 'degraded' : 'healthy',
      healthyServices: healthy,
      degradedServices: degraded,
      unhealthyServices: unhealthy,
      totalServices: servicesData.length,
    },
    metrics: {
      requestRateRps: totalRps,
      requestRateChangePercent: 12.4,
      errorRatePercent: parseFloat(avgErrorRate.toFixed(2)),
      errorRateChangePercent: -0.4,
      latencyP50Ms: Math.round(avgP50),
      latencyP95Ms: 160,
      latencyP99Ms: maxP99,
      latencyChangePercent: 8.2,
    },
    telemetryTrends: {
      requestRateSeries: generateTimeSeries(24, totalRps, 600, 400),
      errorRateSeries: generateTimeSeries(24, avgErrorRate, 0.4, -0.1),
      latencyP99Series: generateTimeSeries(24, maxP99, 120, 80),
      latencyP50Series: generateTimeSeries(24, avgP50, 4, 1),
    },
    activeAlerts: activeAlertsCount,
    criticalAlerts: criticalAlertsCount,
    openIncidents: openIncidentsCount,
    activeSev1Incidents: sev1Count,
    slosAtRisk: slosData.filter((s) => s.status === 'at_risk').length,
    slosBreached: slosData.filter((s) => s.status === 'breached').length,
    recentAlerts: alertsData.slice(0, 5),
    recentIncidents: incidentsData.slice(0, 5),
    services: servicesData,
    slos: slosData,
    recentLogs: logsData.slice(0, 6),
    recentTraces: tracesData.slice(0, 4),
    generatedAt: new Date().toISOString(),
  };
}
