apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudpulse-web
  namespace: cloudpulse
  labels:
    app.kubernetes.io/name: cloudpulse-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: cloudpulse-platform
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudpulse-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudpulse-web
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: cloudpulse-workloads
      securityContext:
        runAsNonRoot: true
        runAsUser: 101 # nginx user in alpine
        fsGroup: 101
      containers:
        - name: web
          image: cloudpulse/cloudpulse-web:v0.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: cloudpulse-web
  namespace: cloudpulse
  labels:
    app.kubernetes.io/name: cloudpulse-web
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cloudpulse-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloudpulse-web-hpa
  namespace: cloudpulse
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudpulse-web
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudpulse-web-pdb
  namespace: cloudpulse
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudpulse-web
