apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudpulse-config
  namespace: cloudpulse
  labels:
    app.kubernetes.io/name: cloudpulse
    app.kubernetes.io/component: configuration
data:
  NODE_ENV: "production"
  PORT: "3001"
  TELEMETRY_MODE: "live"
  API_VERSION: "v1"
  CORS_ORIGIN: "*"
  
  # Kubernetes In-Cluster Service DNS Endpoints
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.cloudpulse.svc.cluster.local:4318"
  PROMETHEUS_URL: "http://prometheus.cloudpulse.svc.cluster.local:9090"
  LOKI_URL: "http://loki.cloudpulse.svc.cluster.local:3100"
  TEMPO_URL: "http://tempo.cloudpulse.svc.cluster.local:3200"
  
  API_GATEWAY_URL: "http://api-gateway.cloudpulse.svc.cluster.local:4000"
  ORDER_SERVICE_URL: "http://order-service.cloudpulse.svc.cluster.local:4001"
  PAYMENT_SERVICE_URL: "http://payment-service.cloudpulse.svc.cluster.local:4002"
